lsst/pipe_tasks

- python/lsst/pipe/tasks/colorterms.py
- python/lsst/pipe/tasks/photoCal.py
- tests/testColorterm.py
PhotoCalTask was mis-calling the Colorterm methods (by providing a filter name,
which is not wanted as of DM-2797).
Also ColortermLibrary.getColorterm was mis-handling glob expressions for the
library name (the arguments to fnmatch.fnmatch were in the wrong order).
> Fix how PhotoCalTask calls Colorterm methods DM-2919

- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/processImage.py
Astrometry tasks have standardized on matchMeta instead
of matchMetadata for returned results. Adapt to that change.
> Change matchMetadata to matchMeta DM-3453

- bin/ingestCalibs.py
- python/lsst/pipe/tasks/ingest.py
- python/lsst/pipe/tasks/ingestCalibs.py
ingest.py is modified slightly for more general use, and ingestCalibs.py is created for parsing through calibration data and creating a calibration registry.
> Tickets/dm-3766: A new Task ingestCalibs

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/coaddBase.py
for assembleCoadd.py
Example-based documentation has been added for the
AssembleCoaddTask class, the SafeClipAssembleCoadd
class and some utility functions in Cooaddbase.py
> DM-4210: Create documentation and examples for SafeClipAssembleCoadd

- python/lsst/pipe/tasks/detectAndMeasure.py
In DetectAndMeasure make sure that all plugins that need aperture-
corrected fluxes get them. This requires running final measurement
in two phases after measuring aperture correction: one to apply
corrections, the other to run all remaining plugins. The need
for this is a misfeature that will be fixed as part of DM-5877.
> Fix a bug in how aperture correction is applied

- python/lsst/pipe/tasks/imageDifference.py
Added config parameter doDipoleFitting (default=True) which if
set to False will fall back on *only* running the previous
DipoleMeasurementTask measurements. If True, it will run
both.
> add DipoleFitTask as default dipole measurement task

- python/lsst/pipe/tasks/detectAndMeasure.py
- python/lsst/pipe/tasks/multiBand.py
The run method of SourceDeblendTask has been updated in the previous
commit to extract the psf from the provided exposure. This commit
updates all calls of the run method to match the new interface.
> Update run method call of SourceDeblendTask

- python/lsst/pipe/tasks/multiBand.py
- tests/testCoadds.py
Measurement algorithm metadata is now captured, added to the source
catalog and succesfully written to disk.
> Capture algorithm metadata in source catalog

- python/lsst/pipe/tasks/imageDifference.py
Fix mixup of var1 and var2 for science and template
> Fix dipoleFitting to use correct matched template exposure

- examples/calibrateTask.py
- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/mocks/mockObservation.py
Update all code that used exposure time or date in Calib,
switching to VisitInfo instead.
> Update for exposure time and date not in Calib

- python/lsst/pipe/tasks/ingest.py
This is used for ingesting MEF files (such as from Decam).
> Make HDU number available to ingest.

- python/lsst/pipe/tasks/characterizeImage.py
useSimplePsf is a boolean; it cannot be set to ``all_iter``.
> DM-8970: Small bug in describing the usesimplePsf config var for charImgTask

- python/lsst/pipe/tasks/characterizeImage.py
Allow doMeasurePsf=False when exposure lacks Psf.
Instead of raising an error, use the Psf implied by installSimplePsf
config variables.
> DM-6045: Nominal PSF required by processCcd

- tests/testPhotoCal.py
tests/testPhotoCal.py: Added compliance to this test for use with
the new matcher and astrometry sourceSelectors used in
matchOptimisticB as implimented in ticket DM-6824.
> DM-6824: Use meas.algorithms.astrometrySourceSelector in measOptimisticB

- tests/testPhotoCal.py
Removed test requirements for the variable nChild.
> tickets/DM-9120: matcherSourceSelector incorrectly uses nChild and footprints in isMultiple test.

- python/lsst/pipe/tasks/multiBand.py
The naming appears to be an error during the port of functionality
from HSC. Renamed in order to make clearer the relationship with the
deepCoadd_meas catalog.
Also renamed the related deepCoadd_srcMatchFull as
deepCoadd_measMatchFull.
> pipe_tasks DM-9885: Rename deepCoadd_srcMatch as deepCoadd_measMatch

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
MakeCoaddTempExp does not require users to know the dimensions of
the model PSF and automatically adjusts the dimensions to match those of
the Warped PSFs. AssembleCoadd now applies the
dimension-adjusted PSF rather than the user-supplied.
> Set the PSF-matched coadd's PSF to the model PSF used

- python/lsst/pipe/tasks/assembleCoadd.py
The previously merged solution to DM-10785 fixed the immediate issue but was not a complete solution.  This change allows the bright object masks to actually be set correctly using the new footprint patterns.
> DM-10785: final correction

- python/lsst/pipe/tasks/multiBand.py
Create the ability to run a fake object task from within the task
to detect sources on coadds. This is useful when starting from
single frames which have already been processed.
> Add fake object hooks to DetectCoaddSources

- python/lsst/pipe/tasks/ingestCalibs.py
The standard pattern will be that calibs are created outside the main
calib directory (e.g., in the rerun) so that they are not immediately
available for use by active processes. Then they need to be transferred
into the calib directory; 'move' is better than 'link' because we will
want to blow away the directory where they were originally created.
> DM-11136: ingestCalibs: change default mode to 'move'

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
We want to be able to control the warping kernel used by CoaddPsf.
Uses the new CoaddPsfConfig class.
> DM-11338: make CoaddPsf configurable

- python/lsst/pipe/tasks/assembleCoadd.py
Specify main stacking statistic in AssembleCoadd and derived tasks
with config parameter `statistic`. For backwards compatibility:
* Setting the deprecated doSigmaClip to True (now False by default)
ignores `statistic` and uses MEANCLIP.
* The default statistic is MEANCLIP imitating the previous default
of doSigmaClip=True.
> Allow configuring more statistical options for assembleCoadd

- tests/testFakeProcessing.py
- tests/testFakes.py
Here is an attempt at fixing the pytest failure with fake mask planes. I remove the FAKE entry in the test  for `testFakeProcessing.py` in the same manner as used in `testFakes.py`. No idea whether this is reasonable but it does work.
Thanks @danielsf for the kick.
> DM-11589: Fix pytest FAKE failure

- python/lsst/pipe/tasks/multiBand.py
Also adds an assert to hopefully keep that bug from happening again.
> Update schema naming conventions to avoid bug in peak culling.

- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/makeDiscreteSkyMap.py
- python/lsst/pipe/tasks/selectImages.py
- tests/test_wcsSelectImages.py
Use of NAXIS1,NAXIS2 is being too familiar with the output format.
lsst.afw.image.bboxFromMetadata allows us to abstract the format.
This is especially important once we activate compression.
> DM-11332: use bboxFromMetadata instead of NAXIS1,NAXIS2

- bin.src/assembleCoadd.py
- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/mocks/mockCoadd.py
* Add new task to compare PSF-matched
warps and identify and mask artifacts when coadding.
* Control warpType by config parameter `warpType`
> Implement CompareWarpAssembleCoaddTask with artifact rejection

- python/lsst/pipe/tasks/processCcd.py
Change to maxFootprintSize is to prevent hangs in deblending.
> Changes to config to make processCcd less prone to failure.

- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/measurePsf.py
- python/lsst/pipe/tasks/photoCal.py
- tests/test_photoCal.py
- tests/test_psfCandidateSelection.py
Change random number generator to afwMath.Random. Sample function had to be
simulated using uniformInt.
Change default to expId=1 for run()(seed=0 is not accepted byafwMath.Random)
Add new unit test for measurePsf to check candidate reserving code.
Add new test to existing testPhotoCal to do the same checks.
Unit tests check reserveFraction and that population changes with expId.
> Fix sampling of reserved candidates to use expId in photoCal, measurePsf

- python/lsst/pipe/tasks/calibrate.py
If adding fake sources are to be consistent in every frame that
goes into a coadd, they must be added after the wcs has been
updated from that inserted by the telescope. This necessitates that
detection and measurement be rerun with the fake sources inserted
> DM-12108: Add fake sources after wcs update

- python/lsst/pipe/tasks/multiBand.py
Without this value, it's difficult to make simulations with the same noise
properties as our coadds.
> DM-6965: DetectCoaddSourcesTask: record variance scaling factor

- python/lsst/pipe/tasks/assembleCoadd.py
that save debug images, including the count image
and the new masks with the additional CLIPPED plane.
> Add debug options to CompareWarpAssemble

- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/mocks/mockCoadd.py
Note that `makeCoaddTempExp` is the only CmdLineTask in this package that actually had an overwrite/clobber option prior to these changes (the rest are all in pipe_drivers), and that's why it's getting special treatment.  While it might be cleanest to have all of these options handled at the same level, I don't want to restructure the code to achieve that now.
> DM-12450: use --reuse-outputs-from instead of doOverwrite options

- python/lsst/pipe/tasks/assembleCoadd.py
SourceDetectionTask adds overhead, but is more configurable.
> Detect artifacts on warpDiffs with SourceDetectionTask

- python/lsst/pipe/tasks/ingest.py
When the input file has been FITS tile-compressed, hdu=0 (which is the
default) is the PHU which has no useful information. We need to specify
hdu=INT_MIN, but that's not possible in python so we just need a
mechanism to signal to leave off the 'hdu' parameter; choose hdu <= 0.
> ingest.py: read metadata from default HDU by default

- python/lsst/pipe/tasks/makeCoaddTempExp.py
Preserve the visitInfo of an exposure when warping.
> Tickets/DM-13325: Set visitInfo of warped exposures.

- python/lsst/pipe/tasks/photoCal.py
Eliminates the possibility of retargeting matching to an incompatible matcher.
> DM-13243: PhotoCalTask must only match with DirectMatchTask

- python/lsst/pipe/tasks/assembleCoadd.py
Because templateCoadd variance is computed as dispersion
of the images, higher sigma will result in a desireable
higher variance in the template.
> Change sigmaclip of template coadd to 5 sigma.

- python/lsst/pipe/tasks/multiBand.py
CoaddPsf is the current tall pole in running measureCoaddSources.
Caching it is simple, inexpensive and realises a hefty gain (25%)
in the runtime.
> DM-13854: measureCoaddSources: add command-line PSF cache configuration

- python/lsst/pipe/tasks/assembleCoadd.py
Overlapping defects can eat up the temporal budget and are excluded
from coadds by their masks. Remove these artifact candidates from the
list before they contribute to the epochCountImage.
> Prefilter artifact candidates based on bad pixel mask

- COPYRIGHT
- doc/lsst.pipe.tasks/index.rst
- python/lsst/pipe/tasks/assembleCoadd.py
The scope of this ticket changed to update only assembleCoadd.py with numpydoc for now.
> DM-13950: Convert assembleCoadd.py to numpydoc

- bin.src/detectDcrCoaddSources.py
- bin.src/measureDcrCoaddSources.py
- bin.src/mergeDcrCoaddDetections.py
- bin.src/mergeDcrCoaddMeasurements.py
- python/lsst/pipe/tasks/dcrMultiBand.py
Extend `multiBand.py` to detect, measure, and merge sources on dcrCoadds.
Note that the two commits in this pull request each represent a different way to accomplish this, and only one of them will be used. 
In the first commit, I simply sub-class each of the necessary Tasks and update a couple methods with new (hard-coded) values. 
In the second commit, I instead replace the existing hard-coded values with dynamic datasetTypes, with defaults that preserve backwards compatibility. This looks neater, but it requires the user to know to specify `--id_dstype=dcrCoadd`, `--id_dstype=dcrCoadd_det`, `--id_dstype=dcrCoadd_calexp`, or `--id_dstype=dcrCoadd_meas` on the command line depending on which Task is being run. 
If the latter approach is strongly preferred, I would appreciate advice on …
> Tickets/DM-14553: Extend `multiBand.py` to work with dcrCoadds.

- bin.src/dumpTaskMetadata.py
- bin.src/reportImagesInPatch.py
- bin.src/reportImagesToCoadd.py
- bin.src/reportPatches.py
- bin.src/reportTaskTiming.py
- doc/old/writeCmdLineTask.dox
- doc/old/writeTask.dox
- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/exampleCmdLineTask.py
- python/lsst/pipe/tasks/getRepositoryData.py
- python/lsst/pipe/tasks/imageDifference.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/makeDiscreteSkyMap.py
- python/lsst/pipe/tasks/makeSkyMap.py
- python/lsst/pipe/tasks/mocks/mockCoadd.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/processCcd.py
- python/lsst/pipe/tasks/transformMeasurement.py
- tests/nopytest_test_coadds.py
- tests/test_processCcd.py
- tests/test_psfCandidateSelection.py
Rename methods according to RFC-352.
Fifteen total repositories with changes.
> DM-2639: {{Standardize primary method names, run/runDataRef, across PipeTasks}}

- python/lsst/pipe/tasks/propagateVisitFlags.py
DM-4878 added a mechanism for propagating flags from the input
visit catalogues to the coadd catalogue indicating stars that
were used for measuring the PSF. Since then, DM-9050 added
similar calibration flags for astrometry and photometry which
are here added to the list of flags that get propagated from
visits to coadds.
A test for the propagation of these flags is in ci_hsc.
> DM-11866: Propagate astrometry and photometry visit calibration flags to coadds

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
These changes provide greater flexibility in applying regularization to DcrModels between iterations and between frequencies, and reduce artifacts in the final images.
> Tickets/dm-15636: Improve DcrModel regularization

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
Some cases errored with mis-matched bounding boxes, and assembling a coadd returned early if the new option `useModelWeights` was turned off.
> DM-16347: Fix modelWeights bugs.

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- tests/test_dcrAssembleCoadd.py
The iterative forward modeling in `DcrAssembleCoadd` requires a gain term to weight the new solution and prevent oscillations. The correct gain can be difficult to guess for a user, but can be calculated from the measured values of convergence of the model using a simple Kalman filter, which is added in this ticket.
> DM-16468: Use measured convergence to predict gain

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
The mask planes were being cleared in the call to `findArtifacts`, and in `CompareWarpAssembleCoadd` they would get added back in during stacking. In `DcrAssembleCoadd`, however, we want to use the full mask plane from the initial non-DCR coadd throughout, because the masked regions would otherwise grow with every iteration. The simple solution implemented here is to copy the mask plane of the initial coadd before `findArtifacts` is run, and use that as the mask. 
Also, the initial coadd is now set to use `CompareWarpAssembleCoadd`.
> DM-16731: Fix DcrCoadd missing mask planes

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
This bug didn't break any unit tests or rebuilding on Jenkins, but showed up when running on data.
> DM-16731 Bug fix: images only support in-place division

- python/lsst/pipe/tasks/mergeMeasurements.py
Runs with similar, but not exact, results to the Gen2 run.
> DM-17412: Converted MergeMeasurementTask to PipelineTask.

- doc/lsst.pipe.tasks/index.rst
Note that this makes no attempt to clean up the many warnings when building the docs for pipe_tasks, but I don't believe it adds any.
> DM-17871: Add DcrAssembleCoaddTask to the API reference

- python/lsst/pipe/tasks/interpImage.py
- tests/test_interpImageTask.py
This allows the interpolation to act over columns instead of rows.
> DM-17428: interpImage: allow transposition before interpolation

- python/lsst/pipe/tasks/objectMasks.py
Andy Goulding has provided new masks based on Gaia DR2, and with a
better tuned size; but the format is subtly different:
* The rotation angle of a 'box' is not specified (it’s supposed to be
zero anyway).
* The 'ID:' string is replaced with 'Gaia DR2'.
* Floating point values use scientific notation in places.
We've decided that (apart from the lack of "ID:", which we want in
order to be explicit) it's best to update the parser rather than fix
the mask files: the differences from what we have been expecting are
reasonable, and fixing the parser now means we may not have to fix
it much for the next version.
Expanded the regex to support the new format, defaulting the
rotation angle of boxes to 0. Added comments to the regex so it's
easier to understand.
> DM-17427: objectMasks: update parser to handle Goulding mask format

- python/lsst/pipe/tasks/measurePsf.py
This was changed to SingleFrameMeasurementTask in the code on DM-1750.
> DM-2944: Remove references to SourceMeasurementTask.

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
Add an option that amplifies the differences between DCR model planes to accelerate convergence. With default settings this is only applied within the footprints of detected sources, and only during the iterative forward modeling step of constructing the DcrModel.
> Tickets/DM-18742: speed up DcrModel convergence

- tests/nopytest_test_coadds.py
This simplifies the code that was wrapping the get() call in a function to turn the result into a list.
> DM-19877: Switch PropertyList.get calls to getArray

- tests/test_processCcd.py
Previously, masking and interpolation was done on a by-defect-type
basis: a set of bad pixels were masked and interpolated, then the
process repeated on different bad pixels. However, this ignores the
case where different types of bad pixels may be contiguous, resulting
in interpolated pixels being derived based on previously interpolated
values.
After reordering, unit test check values are slightly different.
> DM-19382: Update test values for ISR masking/interp changes.

- python/lsst/pipe/tasks/imageDifference.py
This PR changes `ImageDifferenceTask` initialization to only create the `refObjLoader` and `astrometer` subtasks if they will be used. This PR makes no attempt to avoid duplicating the logic that controls which subtasks are used; that's better left to a general refactoring of `ImageDifferenceTask`.
> DM-18394: Crash when running ap_pipe on calexp templates

- python/lsst/pipe/tasks/multiBand.py
We can't generate a denormalised match list from no matches,
because we don't have the schemas (which come from the matches);
so lsst.meas.astrom.denormalizeMatches raises RuntimeError if
there are no matches. We need to catch this case before calling
denormalizeMatches.
> DM-20472: measureCoaddSources: fix error from empty matches

- python/lsst/pipe/tasks/deblendCoaddSourcesPipeline.py
This makes the Gen3 PipelineTask mirror the Gen2 CmdLineTask, and ensures the same objects are deblended in each band.
> DM-20705: Set config default to propagate all peaks in coadd deblending.

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
The old version of this code assumed that there was a unique visit number for each patch, which was true for the test data that had only one CCD. When there are multiple CCDs contributing to a patch, however, they may all have the same visit number and the exposure catalog will have as many entries as the number of visits times the number of CCDs.
> DM-20929: Fix bug in DcrAssembleCoaddTask

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/deblendCoaddSourcesPipeline.py
- python/lsst/pipe/tasks/insertFakes.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/mergeDetections.py
- python/lsst/pipe/tasks/mergeMeasurements.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
During transition to gen3 middleware some tasks were converted to in-progress PipelineTask API. This ticket converts those tasks to the API that is expected to be used going forward.
> DM-20692: Update existing PipelineTasks to new API

- python/lsst/pipe/tasks/read_defects.py
We tend to use camelCase for directory names but we want the name of the instrument in the ecsv defect files to match the name of the instrument reported by the translator and/or INSTRUME header.
It seems highly unlikely that we would think it's an error for a LATISS observation to be in a latiss directory so this change lower cases the instrument names before comparing.
This change supports lsst/obs_lsst_data#1
> DM-21186: Use case insensitive instrument consistency check

- python/lsst/pipe/tasks/assembleCoadd.py
We were growing the artifacts too much w.r.t.
the footprints in the template. Shink nSigmaToGrow
on the warp detections to increase depth and produce
fewer stars with inexact_psf. Simultaneously, increase
the nSigmaToGrow on the static sky template to the
default 2.4 sigma. This better protects the cores of
bright stars from clipping.
> DM-20775: Grow artifacts by fewer pixels.

- tests/nopytest_test_coadds.py
This saves 200MB in the installed footprint.  The test data are
not deleted if a test fails.
> DM-22796: Rearrange test so that temp data files are removed if tests pass

- python/lsst/pipe/tasks/multiBand.py
While porting to scarlet 1.0 `meas_extensions_scarlet` fixed
a bug where the `deblend` module contained a `deblend` function
that overwrote the module. The `__init__.py` was modified to
import the module, not the internal classes and functions into
the root namespace.
> Update API for ScarletDeblendTask

- python/lsst/pipe/tasks/imageDifference.py
* Add connection and minimal definition of inputs and outputs.
* Add skymap as a task dimension, we do not support multiple skymaps in one run.
> DM-22541 Add initial gen3 support to ImageDifferenceTask.

- python/lsst/pipe/tasks/calibrate.py
- tests/test_calibrate.py
This PR fixes some connection-handling logic in `CalibrateTask`. The changes to the task itself are straightforward; most of the code changes are from creating a new unit test framework for `CalibrateTask` and creating enough mock data to satisfy `CalibrateTask.runQuantum`.
> DM-23616: Run converted ap_verify testdata through gen3 pipeline

- python/lsst/pipe/tasks/read_curated_calibs.py
I was confused about the purpose of the CALIBDATE metadata value
when I initially implemented this reader.  The valid date
comes from the file name and the CALIBDATE is a label for the
dataset produced by the pipeline.
> DM-24027: Remove comparison of CALIBDATE to the valid start

- python/lsst/pipe/tasks/functors.py
- tests/test_functors.py
> DM-23946: Change localWcs plugins to use a localGnomonicWcs transform.

- tests/test_functors.py
- tests/test_parquet.py
- tests/test_transformObject.py
pyarrow was unavailable on macos. This workaround allowed us to
test on linux only, but is no longer necessary.
> DM-22256: Remove skipUnless pyarrow available

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
This just copies code from `AssembleCoaddTask.runDataRef` to `DcrAssembleCoaddTask.runDataRef`, and replaces the call to `AssembleCoaddTask.runDataRef` with `self.run`.
> DM-23498: Modifications to enable PSF-matched DCR coadds

- python/lsst/pipe/tasks/characterizeImage.py
In Gen3 (at least), visits are on-sky, and possibly combinations of snaps; ISR runs on exposures.
> DM-15536: Switch postISRCCD to use exposure, not visit.

- pipelines/VisualizeVisit.yaml
- python/lsst/pipe/tasks/visualizeVisit.py
Add gen3 implementation of visualizeVisit.
> DM-22643: convert visualizeVisit to gen3

- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/imageDifference.py
Also includes a small bug fix in `dcrAssembleCoadd` that was necessary for the simplified test dataset to run.
> DM-22952: Gen 3 version of DCR image differencing

- bin.src/makeGen3DcrSubfilters.py
- bin.src/makeGen3Skymap.py
Checks are made against local filesystem only. This stopped being a valid assumption since S3Datastore was implemented as the data repository does not need to be local anymore.
The failure case should be handled internally by Butler itself at instantiation time.
These check currently block executing `makeGen3SkyMap` if the location of the data repository is in S3 (f.e. `s3://bucketname/`). 
The errors raised by the butler are either `RuntimeError` if the butler config file is of unknown format or `FileNotFoundError` if it's not at the given location. I think this is fine, but if required I think it should be possible to reinstate the exact error messages as before by attempting to instantiate a Butler, catching the exceptions and then printing and exiting with error code 1.
> DM-24290: Remove if Butler exists checks from bin.src scripts.

- python/lsst/pipe/tasks/insertFakes.py
Add documentation to `calibFluxRadius` config and code comments explaining scaling of the simulated flux to mach the calibration aperture radius.
The same thing is done for stars and galaxies.  
I put in two identical comment blocks so that this PR is a comment-only change.
Ideally I would have liked to refactor slightly to make one function that's called by each of the mkGalaxies and mkStars method.  Let me know if you want me to go in that direction.
> Improve explanation of scaling of PSF kernel to match aperture calibration radius

- python/lsst/pipe/tasks/postprocess.py
by WriteSourceTable to retrieve local PhotoCalib/Wcs columns.
This feature is limited and only for creating transformed
source tables from older afw src tables that do not contain
local calib columns.
> DM-24379: Add config options to read PhotoCalib or Wcs from calexps

- python/lsst/pipe/tasks/imageDifference.py
This PR adds the output catalog schema as a Gen 3 connection for `ImageDifferenceTask`. The `getSchemaCatalogs` method has been reimplemented in terms of the Gen 3 schema, on the assumption that the former will be going away while the latter is permanent.
> DM-21939: Create Gen 3 AP Pipeline

- python/lsst/pipe/tasks/ingest.py
The getExtension method during ingestion is only used for multi-extension FITS files, and in practice that means DECam. The method was not behaving as advertised and was overridden in both ingest and ingestCalibs in obs_decam. Those overrides have been removed and the method here in pipe_tasks now works as intended.
> DM-17538: Generate stack-produced (rather than CP) calibration products for DECam

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- tests/assembleCoaddTestUtils.py
- tests/test_assembleCoadd.py
This creates mock data references that mimic the API of the Gen 2 and Gen 3 butler in order to pass simulated test data to AssembleCoaddTask without having to instantiate a real Butler. I have only written fairly basic unit tests to demonstrate their use, but they exercise most of the coadd assembly code and work through the difficult part of getting the metadata set up properly.
> DM-24731: Create a unit test framework for AssembleCoaddTask

- python/lsst/pipe/tasks/ingestCalibs.py
Remove single-day gaps in validation ranges.
> DM-26171: calibrations cannot be retrieved on the last day of a validity range

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/imageDifference.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/transformMeasurement.py
This PR adds `@timeMethod` decorators to the `run` methods of tasks that had them in Gen 2.
> DM-21919: Run ap_verify end-to-end in Gen 3

- python/lsst/pipe/tasks/characterizeImage.py
In very crowded fields, the cosmic ray detection algorithm can fail if it doesn't have a good PSF. We do an initial CR detection at the start of each iteration of measuring the PSF in image characterization, which means it uses the default PSF for the first iteration. By simply skipping CR masking if it fails at this stage we can get an improved PSF model, which can be used to perform CR masking in subsequent iterations.
> DM-26586: Skip initial cosmic ray detection if it fails

- python/lsst/pipe/tasks/functors.py
- tests/test_functors.py
This adds a .difference method to Functor, which computes
the difference between the functor called on one ParquetTable
and another.  Will be useful in future for pipe_analysis compare* scripts.
> DM-27003: add difference method to functor, and a test

- python/lsst/pipe/tasks/cli/cmd/commands.py
- tests/test_cliCmdMakeDiscreteSkymap.py
It was changed from an option.
> DM-26874: rename pipetask2 to pipetask, remove old pipetask

- python/lsst/pipe/tasks/ingestCalibs.py
Add incrementValidEnd option to determine how validEnd is treated.
> DM-27165: Calibration ingestion produces registry where butler cannot find matching calib product

- python/lsst/pipe/tasks/imageDifference.py
This change adds a doScaleDiffimVariance config option, which was set True for this ticket's ap_pipe rerun.
> DM-25990: Reprocess HSC COSMOS medium dataset with ap_pipe

- python/lsst/pipe/tasks/multiBandUtils.py
End usage of FilterProperty, as per RFC-730.
Usage in dcrAssembleCoadd.py left as it is dealt with by DM-26615.
> DM-27168: Phase out use of FilterProperty

- python/lsst/pipe/tasks/cli/cmd/commands.py
Make subclass commands ButlerCommands, which add a note to the
subcommand help that says "See butler --help for more options."
> DM-27500: add a comment in butler & pipetask subcommand about more options in butler --help

- python/lsst/pipe/tasks/ingest.py
Fix headers as originally intended during raw ingest.
> DM-24253: Generate stack produced calibration products for HiTS

- python/lsst/pipe/tasks/functors.py
- tests/test_functors.py
For gen3 compatibility, this allows for a DeferredDatasetHandle to be be passed to a functor's __call__ method, rather than the
gen2 parquet interface ParquetTable object.  All currently tested Functor functionality is also tested here for the gen3 model.  Backward compatibility with gen2 is maintained.  N.B.: the gen3 functor performance will likely be slower than the gen2 performance; remains to be seen if this matters at all.
> DM-27008: Allow a DeferredDatasetHandle to be passed to a Functor

- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/parquetTable.py
- tests/test_functors.py
For gen3 compatibility, this allows for a DeferredDatasetHandle to be be passed to a functor's __call__ method, rather than the gen2 parquet interface ParquetTable object.  All currently tested Functor functionality is also tested here for the gen3 model.  Backward compatibility with gen2 is maintained.  N.B.: the gen3 functor performance will likely be slower than the gen2 performance; remains to be seen if this matters at all.
Further note, this commit had previously broken ci_hsc because of one line where I had accidentally left a `raise` instead of continuing on to use a `.fail()` method (had been in there for debugging purposes and removal should pass ci_hsc).
> Allow a DeferredDatasetHandle to be passed to a Functor

- bin.src/processBrightStars.py
- python/lsst/pipe/tasks/processBrightStars.py
Main PR out of the 4 for [DM-25304](https://jira.lsstcorp.org/browse/DM-25304), the others being daf_butler, obs_base and obs_subaru.
Jenkins run [#32381](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/32381/pipeline).
> DM-25304: Add task to extract and process bright stars

- python/lsst/pipe/tasks/assembleCoadd.py
- tests/test_assembleCoadd.py
This reverts the changes from DM-24731 to `SafeClipAssembleCoaddTask` that converted the computation of `coaddMean` and `coaddClip` to use subtasks. I had thought that it was necessary to use subtasks in order to run mock versions of the tasks in unit tests, but the tests currently pass with those changes reverted. Reverting the changes better ensures that the `coaddMean` and `coaddClip` are computed using the correct config settings from `SafeClipAssembleCoaddTask`
> DM-28103: Revert changes to use subtasks from DM-24731

- python/lsst/pipe/tasks/imageDifference.py
This PR adds units of "count" to instFlux and instFluxErr. Previously, they errantly had no units.
> DM-26372: Units wrong in deepDiff_diaSrc catalog

- python/lsst/pipe/tasks/functors.py
- tests/test_functors.py
Previous updates to Functor to allow for passing a DeferredDatasetHandle did not have appropriate logic to allow for the handle to point to a dataframe with only a single-level column index.  This corrects that, and adds corresponding tests, which were also missing before (which is why this bug was not caught).
> DM-28922: Correct functor logic to work with single-level datarefs, and add tests

- python/lsst/pipe/tasks/processBrightStars.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-25894)
[Jenkins run #33446](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/33446/pipeline)
> DM-25894: Extract stars on, or slightly beyond, exposure edge

- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/selectImages.py
* Refactor SelectImageTasks, adding a run method that takes lists
of calexp properties. runDataRef remains the Gen2 entry point
which still takes dataRefs.
* MakeWarp now calls the configured selectImages subtask in
runQuantum. The calexp list was changed to deferLoad, because the padding
needed in the gen3 skymap is providing many more calexps than actually
overlap the patch. Loading is performed after image selection is run,
so that only the calexps that will be used are loaded into memory.
> DM-20695: Convert SelectImageTasks to Gen3

- python/lsst/pipe/tasks/processBrightStars.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-28600)
Jenkins run [#33511](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/33511/pipeline)
> DM-28600: Add option to apply skyCorr to ProcessBrightStarsTask

- python/lsst/pipe/tasks/quickFrameMeasurement.py
- tests/test_quickFrameMeasurement.py
This is an experimental task with a potentially volatile API
which should not yet be relied upon, i.e. its API is subject to
change without RFC as its primary purpose is in observing scripts
written by T&S.
The tasks goal is to, given a postISR image, quickly and robustly
find the centroid of the brightest star in the image.
> DM-27652: Write the QuickFrameMeasurementTask and unit tests.

- python/lsst/pipe/tasks/configurableActions/__init__.py
- python/lsst/pipe/tasks/configurableActions/_configurableAction.py
- python/lsst/pipe/tasks/configurableActions/_configurableActionField.py
- python/lsst/pipe/tasks/configurableActions/_configurableActionStructField.py
- tests/test_configurableActions.py
Add new Config and Field types. These config types known as
ConfigurableActions, are callables that can have state specified
at configuration time. Two container Fields,
ConfigurableActionField and ConfigurableActionStructField are
introduced to allow adding ConfigurableActions to Config classes.
These classes are meant to serve as the basis for future work on
specific actions to interact with DataFrames.
> tickets/DM-29031 Add new Config and Field types

- python/lsst/pipe/tasks/quickFrameMeasurement.py
- tests/test_quickFrameMeasurement.py
SdssCentroids fit donuts very poorly, and a simple CoM
centroid provides a pretty robust measurement when seeded
with the position using the existing algorithm.
This is not expected to deal with overlapping donuts as it
is used to simply to give a cutout to CWFS analysis.
> DM-29673 Add centre of mass centroiding to support donut images

- python/lsst/pipe/tasks/extended_psf.py
- tests/test_extended_psf.py
Main PR for [DM-29583](https://jira.lsstcorp.org/browse/DM-29583?jql=assignee%20%3D%20currentUser()%20AND%20resolution%20%3D%20unresolved%20ORDER%20BY%20priority%20DESC%2C%20created%20ASC), the other being in daf_butler.
Jenkins run [#33904](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/33904/pipeline) contains these changes, plus those of [DM-25305](https://jira.lsstcorp.org/browse/DM-25305) (ticket was split in two).
> DM-29583: Create dataset class for extended PSF models

- python/lsst/pipe/tasks/extended_psf.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-25305); Jenkins run [#33904](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/33904/pipeline).
~Main one of two PRs, the other being in daf_butler~
(edit: the daf_butler PR has now been moved to DM-29583)
> DM-25305: Add stacking of saved bright star stamps to build extended PSF model

- python/lsst/pipe/tasks/healSparseMapping.py
The butler formatters expect to be able to overwrite data.
> DM-29883: Add keyword to always overwrite existing files.

- python/lsst/pipe/tasks/deblendCoaddSourcesPipeline.py
The current gen3 pipeline does not update the catalog with the
last source id in the mergeDet catalog, so if there were any
merged peaks culled then the next source id starts too low,
resulting in a catalog that is not sorted with some duplicate
entries.
This commit fixes that by notifying the idFactory of the largest
source id.
> DM-29907: Update the idFactory for the deblender input catalog

- python/lsst/pipe/tasks/imageDifference.py
This PR makes `doScaleDiffimVarianceTask` True to be the new default behavior in imageDifferenceTask. We won't need to override this config in any pipeline or ap_verify-style dataset to get consistent results.
> DM-29344: Investigate the CI differences between Gen 2 and 3 in COSMOS field

- pipelines/DRP.yaml
Add TransformDiaSourceCatalogTask to DRP pipeline.
> DM-30149: Check if the TransformDiaSourceCatalog pipeline task can be used on DC2 data for use in DP0

- ups/pipe_tasks.build
- ups/pipe_tasks.cfg
This PR fixes a build error caused by converting `pipe_base` to a pure-Python package in lsst/pipe_base#184.
> DM-23330: Doxygen warnings in pipe_base

- pipelines/DRP.yaml
- python/lsst/pipe/tasks/imageDifference.py
move some task defaults from DRP.yaml to setDefaults in imageDifference.py. Should be quick.
> DM-29869: Make doScaleDiffimVariance=True the default in ImageDifferenceTask

- python/lsst/pipe/tasks/dataFrameActions/__init__.py
- python/lsst/pipe/tasks/dataFrameActions/_actions.py
- python/lsst/pipe/tasks/dataFrameActions/_baseDataFrameActions.py
- python/lsst/pipe/tasks/dataFrameActions/_evalColumnExpression.py
This commit introduces a base class for configurable actions that
works on Data Frames, basic concrete actions, and some supporting
functions.
> tickets/DM-29728 Introduce configurable actions for DataFrames

- python/lsst/pipe/tasks/mergeDetections.py
Allows the user to match two catalogs that are derived from the same mergeDet catalog.
> tickets/DM-27800: Create matchCatalogsExact function

- python/lsst/pipe/tasks/ingestCalibs.py
- python/lsst/pipe/tasks/read_curated_calibs.py
Add support for curated brighter-fatter kernels.
> DM-30351: Make sure brighter-fatter correction is working on DC2 data for DP0.2

- python/lsst/pipe/tasks/insertFakes.py
Above error occasionally encountered when evaluating a
CoaddPsf in a region with no underlying exposures.
> DM-30560: Handle cases of incomputable Psfs in source injection

- python/lsst/pipe/tasks/matchFakes.py
- tests/test_matchFakes.py
This PR moves `MatchApFakesTask` from `ap_pipe` and renames it to `MatchFakesTask` (see lsst/ap_pipe#82).
The one significant change to the code is fe9feef, which rewrites the unit test for `MatchApFakesTask` to not depend on `CreateRandomApFakesTask`. This involves hard-coding some of the details of the fakes catalog schema into the test.
> DM-30776: Move MatchApFakesTask to pipe_tasks

- doc/conf.py
- doc/lsst.pipe.tasks/index.rst
- doc/lsst.pipe.tasks/tasks/lsst.pipe.tasks.metrics.NumberDeblendChildSourcesMetricTask.rst
- doc/lsst.pipe.tasks/tasks/lsst.pipe.tasks.metrics.NumberDeblendedSourcesMetricTask.rst
- python/lsst/pipe/tasks/metrics.py
- setup.cfg
- tests/test_metrics.py
This PR implements two new deblending-related metrics defined in lsst/verify_metrics#27.
> DM-27032: Create deblended source metric

- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/computeExposureSummaryStats.py
- python/lsst/pipe/tasks/postprocess.py
- tests/test_processCcd.py
The ComputeExposureSummaryTask has also been moved from characterize to calibrate, where it should be to have the latest-and-greatest photometric calibration and wcs.  In the previous location it was computing incorrect values.
> DM-30701: Add astromOffsetMean and astromOffsetStd to ExposureSummaryStats.

- python/lsst/pipe/tasks/processBrightStars.py
One of two PRs for DM-26651, [the other ](https://github.com/lsst/meas_algorithms/pull/247)being in meas_algorithms.
[Jira ticket](https://jira.lsstcorp.org/browse/DM-26651)
[Jenkins run](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/34567/pipeline)
> DM-26651: Persist individual bright stars' warping Transforms, origin and number of rotations

- doc/lsst.pipe.tasks/tasks/lsst.pipe.tasks.postprocess.WriteSourceTableTask.rst
- python/lsst/pipe/tasks/matchFakes.py
- python/lsst/pipe/tasks/postprocess.py
This PR fixes some incorrect documentation for `MatchFakesTask` and `WriteSourceTableTask` found while working on DM-30349.
> DM-30349: Documentation fixes

- python/lsst/pipe/tasks/deblendCoaddSourcesPipeline.py
Sometimes inputs to the deblender are missing due to previous tasks
not producing them. This means the corresponding output catalog will
not be present. Adjust the 'put' logic in DeblendCoaddSourcesMultiTask
such that missing datasets will be set to None.
> Dm-31275 Allow for missing inputs when deblending

- python/lsst/pipe/tasks/assembleCoadd.py
The situation can occur where a given visit specified in the list
of selected visits is missing from the inputWarpDict for a given
tract/patch dataRef.  Thus, check that the visit actually exists
in the inputWarpDict before trying to append it to the filtered
inputs list.
> DM-31376: :assembleCoadd can't handle when selectVisit selects a visit with no Warp

- python/lsst/pipe/tasks/deblendCoaddSourcesPipeline.py
When deblending it is possible some inputs were not produced in
previous steps, and thus no outputs were created corresponding
to those inputs. Explicitly call put on the outputs that could
be produced.
> Dm-31360 Explicitly put each Scarlet catalog

- pipelines/DRP.yaml
- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/postprocess.py
- tests/test_transformObject.py
This series of tasks produces the ForcedSource table
specified in the DPDD.
> DM-28394: Add Tasks to write, transform, and consolidate ForcedSources

- pipelines/DRP.yaml
- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/postprocess.py
- Generalize the write|transform|consolidateForcedSourceTasks to
work regardless of reference catalog used to seed the forced phot.
- Make the error message more clear if a requested column is missing.
> DM-31765: Transform forced sources on diaObjects during DRP

- pipelines/DRP.yaml
- python/lsst/pipe/tasks/drpAssociationPipe.py
- python/lsst/pipe/tasks/drpDiaCalculationPipe.py
- python/lsst/pipe/tasks/postprocess.py
- python/lsst/pipe/tasks/simpleAssociation.py
- tests/test_simpleAssociation.py
- tests/test_transformObject.py
* all dataframes have primary keys as index only
* all final parquet table dataset names start with lowercase and end with `Table_visit` or `Table_tract` depending if its a visit or tract level dataset 
* object table columns look like `g_apFlux` instead of `gApFlux`
* All per-patch datasets are consolidated into a per-tract dataset
I promise to squash these before merging
> DM-31825: Implement RFC-807 on  DRP DataFrame consistency

- python/lsst/pipe/tasks/makeCoaddTempExp.py
- tests/test_coaddInputs.py
This PR uses the `id` component added on lsst/afw#613.
> DM-29955: Add ExposureInfo id getter

- python/lsst/pipe/tasks/imageDifference.py
This PR removes uses of `VisitInfo.getExposureId()`, which was deprecated in lsst/afw#614.
> DM-13943: Deprecate VisitInfo.getExposureId()

- python/lsst/pipe/tasks/imageDifference.py
PSF.computeShape without a PSF is deprecated. I do want it to evaluate on average position, but make it explicit.
> DM-31777: Add explicit avg position to psf shape call.

- python/lsst/pipe/tasks/imageDifference.py
- psf.computeShape without a position is deprecated RFC-796
- also remove unnecessary recomputation of shape. templateSigma
is available to whole AL section.
> DM-31777-v23: Add explicit avg position to psf shape call.

- python/lsst/pipe/tasks/computeExposureSummaryStats.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/postprocess.py
- python/lsst/pipe/tasks/selectImages.py
This PR moves the gen3 `PsfWcsSelectImagesTask` to using the visitSummary table and removes the source connection, which should speed up i/o.  
For gen2, we don't have the visitSummary tables so I left in the legacy computation, and this can be removed with the rest of the gen2 code when the time comes.
> DM-32649: Add psf size and shape residual statistics to visitSummary

- python/lsst/pipe/tasks/makeCoaddTempExp.py
The mi reference was being superseded by the application of the photometric
calibration, and thus the skyCorr correction was applied to a ghost image
array and not to the returned calexp.
> DM-32827: Explicitly apply operations to calexp.maskedImage.

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/selectImages.py
- tests/surveyPropertyMapsTestUtils.py
- tests/test_coaddInputs.py
- tests/test_processCcd.py
Note that the changes to ImageDifferenceTask are being done separately on DM-31777.
> DM-32549: Supply position for psf shape computations

- python/lsst/pipe/tasks/makeCoaddTempExp.py
The mi reference was being superseded by the application of the photometric
calibration, and thus the skyCorr correction was applied to a ghost image
array and not to the returned calexp.
> DM-32827-v23: Explicitly apply operations to calexp.maskedImage. 

- python/lsst/pipe/tasks/matchFakes.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
- tests/test_matchFakes.py
Add code to concatenate fake catalogs.
Fix linting.
Add compose fakes to variablity code.
Debug matchFakes.
Add docs
Simplify unittests.
Remove unnessecary runQuantum test.
Change coding dimensions.
Fix linting.
Output tract numbers.
Fix linting.
Access tractId
Access tractId
Fix ra/decColName usage.
> DM-31964: Fixup dimensions on ProcessCcdWithFakesTask/MatchFakesTask

- python/lsst/pipe/tasks/insertFakes.py
This PR edits the deprecation messages for old `InsertFakesTask` config fields to provide the correct replacement names.
> DM-33010: Fix typo in deprecation message.

- python/lsst/pipe/tasks/imageDifference.py
This could also have been written to instead use `self.astrometer`, though that would not pick up the custom config value for the matcher.
> DM-13899: Fix AstrometryTask API in ImageDifferenceTask

- python/lsst/pipe/tasks/mocks/simpleMapper.py
The options are continually copied over and continually
checked for python type to PropertySet type. It is much more
efficient to cache a PropertySet and copy that PropertySet
in to the hierarchy each time.
> DM-33478: Cache the write_options in the Mock

- python/lsst/pipe/tasks/insertFakes.py
- python/lsst/pipe/tasks/matchFakes.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
to InsertFakesTask and MatchFakesTask respectively
- insertOnlyStars: allows galaxy parameters to be absent from catalogs
- doMatchVisit: filters synthetic sources by visit number.
> DM-33327 (to merge): Add config options insertOnlyStars and doMatchVisit

- doc/lsst.pipe.tasks/tasks/lsst.pipe.tasks.isolatedStarAssociation.IsolatedStarAssociationTask.rst
- python/lsst/pipe/tasks/isolatedStarAssociation.py
- tests/test_isolatedStarAssociation.py
This PR adds a new isolated star association task for input to re-estimating the psf with consistently reserved stars, and for input to fgcmcal.
Note that the `Matcher` code currently in the commit is just there for testing purposes until DM-33545 is finished and we have a new env with `spherematch`.
> DM-33279: Add IsolatedStarAssociationTask

- python/lsst/pipe/tasks/assembleCoadd.py
because log.fatal does not exit.
There is still a log.debug that prints each bbox in the loop
if more info on which subregion it is working on is needed.
> DM-33786: Remove try block for stacking

- python/lsst/pipe/tasks/assembleCoadd.py
because log.fatal does not exit.
There is still a log.debug that prints each bbox in the loop
if more info on which subregion it is working on is needed.
> DM-33786-v23: Remove try block for stacking

- python/lsst/pipe/tasks/insertFakes.py
- python/lsst/pipe/tasks/matchFakes.py
Current status has fixes from pair coding with @ebellm @sr525 and me. We added RA + Dec filtering prior to inserting and matching fakes, so fake sources far from the sky region under consideration are never used.
I intend to rerun matchFakesTask on the ~recent large HSC and DECam ApPipe reruns and see if the problems pertaining to completeness and fakes showing up in ridiculous places go away.
> DM-31388: Investigate low fake injection completeness in HSC COSMOS

- python/lsst/pipe/tasks/cli/cmd/commands.py
- python/lsst/pipe/tasks/script/makeDiscreteSkyMap.py
> DM-34105: Take into account move of Instrument from obs_base to pipe_base

- python/lsst/pipe/tasks/configurableActions/_configurableActionStructField.py
- tests/test_configurableActions.py
This ticket fixes some assignment logic in ConfigurableActionStructField wherein a local copy of a ConfigurableActionStruct was not being made, leaving a dangling reference to a config object that goes out of scope.
This ticket also makes a change to stay in line with other pex_config fields wherein it takes other python classes that duck like a ConfigurableActionStructField as an argument in assigment.
Finally this ticket adds a verification that a string used in the dict update interface is a valid python identifier.
> tickets/DM-33977 Fixes for ConfigurableActionStructField

- python/lsst/pipe/tasks/imageDifference.py
The new GetTemplateTask no longer uses `coaddName` as a config parameter
> DM-33745: Remove validation check for GetTemplate.coaddName

- python/lsst/pipe/tasks/multiBand.py
There was previously no way to run a task on the `deblendedModel` outputs from `ScarletDeblendTask`. This commit allows the user to choose whether to run measurement on the scarlet models or flux re-distributed models.
> DM-33834: Fix bug to run on scarlet models

- doc/doxygen.conf.in
- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/diff_matched_tract_catalog.py
- python/lsst/pipe/tasks/exampleCmdLineTask.py
- python/lsst/pipe/tasks/exampleStatsTasks.py
- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/measurePsf.py
- python/lsst/pipe/tasks/mergeDetections.py
- python/lsst/pipe/tasks/mergeMeasurements.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/multiBandUtils.py
- python/lsst/pipe/tasks/photoCal.py
- python/lsst/pipe/tasks/processCcd.py
- python/lsst/pipe/tasks/propagateVisitFlags.py
- python/lsst/pipe/tasks/repair.py
- python/lsst/pipe/tasks/snapCombine.py
- python/lsst/pipe/tasks/transformMeasurement.py
- tests/test_finalizeCharacterization.py
- ups/pipe_tasks.cfg
This PR cleans up a very long list of Doxygen errors in `pipe_tasks`, as well as some unrelated warnings that were easy fixes. Given the ongoing (if stalled) documentation migration, I've prioritized error-free builds over correct ones, intervening for correctness only if I found an issue that badly corrupted the documentation (e.g., failure to properly close `@link` tags).
While few of the fixes overlap, some of them are non-obvious, so I recommend reviewing this PR commit-by-commit for context.
> DM-33157: Fix doxygen errors in pipe_tasks

- python/lsst/pipe/tasks/imageDifference.py
Decorrelation is supposed to correct the correlated noise caused by convolving the template with the PSF matching kernel, so we need to actually supply the PSF-matched template to the calculation. Currently we are passing in the warped, but not PSF-matched, template.
> DM-34364: Use the PSF-matched template for decorrelation

- python/lsst/pipe/tasks/postprocess.py
- Split functionality to reevaluate calibs by rerunning plugins
base_LocalWcs and base_LocalPhotoCalib
into a subclass WriteRecalibratedSourceTable
- move configs doApplyExternalPhotoCalib and doApplyExternalSkyWcs
to subclass.
- Add ability to configurably apply global calibrations from e.g.
jointcal and FGCM.
> DM-34466: Port functionality to reevaluate calibs in writeSourceTable to gen3

- python/lsst/pipe/tasks/postprocess.py
- Split functionality to reevaluate calibs by rerunning plugins
base_LocalWcs and base_LocalPhotoCalib
into a subclass WriteRecalibratedSourceTable
- move configs doApplyExternalPhotoCalib and doApplyExternalSkyWcs
to subclass.
- Add ability to configurably apply global calibrations from e.g.
jointcal and FGCM.
> DM-34466-v23: Port functionality to reevaluate calibs in writeSourceTable to gen3

- python/lsst/pipe/tasks/postprocess.py
Switch configs to reEval and doApplyExternal to True
Almost every time this task will be used after DP0.2
will be to apply jointcal/FGCM calibrations to the
source tables
> DM-33959: Calibrate Source Tables with Global Calibrations

- python/lsst/pipe/tasks/isolatedStarAssociation.py
The smatch API for matching a catalog to itself is changing in a breaking way for the upcoming 0.10 version.  The current rubin-env is pinned so that it won't be updated without us deliberately making the update.  This PR adds support for both the old and the new API, to smooth this transition.
> DM-35083: Add support for new and old smatch grouping API.

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/coaddInputRecorder.py
- python/lsst/pipe/tasks/dcrAssembleCoadd.py
- python/lsst/pipe/tasks/hips.py
- python/lsst/pipe/tasks/insertFakes.py
- python/lsst/pipe/tasks/makeCoaddTempExp.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/photoCal.py
- python/lsst/pipe/tasks/postprocess.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
- tests/assembleCoaddTestUtils.py
- tests/test_coaddInputs.py
- tests/test_hips.py
- tests/test_photoCal.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
> DM-27177: Deprecate transitional getFilterLabel API

- python/lsst/pipe/tasks/configurableActions/_configurableActionStructField.py
Fields were not being properly initialized empty when serialized.
This caused state from a defaunt instatiation of a class to add
state back into a de-serialized object when it should not be
there.
> DM-35386 Fix Serialization of ConfigurableActionStructField

- python/lsst/pipe/tasks/processCcdWithFakes.py
This is part of meas_base gen2 removal. It was used in the gen2
argument parser which is no longer functional.
> DM-35725: Remove usage of PerTractCcdDataIdContainer

- COPYRIGHT
- python/lsst/pipe/tasks/metrics.py
- tests/test_metrics.py
This PR removes use of the `lsst.verify.gen2tasks.register` decorator, which is removed in lsst/verify#103.
> DM-33256: Remove Gen 2 support from verify

- python/lsst/pipe/tasks/metrics.py
- tests/test_metrics.py
This PR removes all code for handling `None` inputs from concrete `MetricTasks` and raises `NoWorkFound` where appropriate.
> DM-30869: Modernize MetricTask for better Gen 3 workflow

- python/lsst/pipe/tasks/postprocess.py
This PR adds the `calexpType` template to the outputs of `MakeCcdVisitTableTask` and `MakeVisitTableTask` (they were added to inputs on 80aa66dc92c83c1e284b116ae07675d6559376d3). This makes it possible run both fakes and non-fakes versions of these tasks in the same pipeline, though the only difference in output should be a few extra columns in the fakes version.
> DM-36198: Allow fakes propagation in postprocessing

- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/mergeDetections.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/multiBandUtils.py
> DM-2850: Remove getSchemaCatalogs methods

- python/lsst/pipe/tasks/loadReferenceCatalog.py
pipelines.lsst.io will not build with two
Parameters sections
> DM-37011-v24: Remove second Parameters section

- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/drpAssociationPipe.py
- python/lsst/pipe/tasks/extended_psf.py
- python/lsst/pipe/tasks/makeWarp.py
- python/lsst/pipe/tasks/matchBackgrounds.py
- python/lsst/pipe/tasks/matchFakes.py
- python/lsst/pipe/tasks/multiBand.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
- python/lsst/pipe/tasks/propagateVisitFlags.py
- tests/assembleCoaddTestUtils.py
- tests/surveyPropertyMapsTestUtils.py
`datasetType` and `immediate` parameters were for gen2 but will imminently not be allowed in gen3 (they are currently ignored).
> DM-37865: Remove unused parameters from deferred dataset handle get calls

- python/lsst/pipe/tasks/drpAssociationPipe.py
- python/lsst/pipe/tasks/matchFakes.py
- python/lsst/pipe/tasks/processCcdWithFakes.py
- tests/test_hips.py
@erykoff The actual driver for this fix is that the tests fail with debug logging because the mocked deferred dataset handle didn't define the dataId as a property.
Fixing DeferredDatasetHandle usage is now in #758.
> DM-38062: Fix dataId property in deferred dataset handle usage

- python/lsst/pipe/tasks/subtractBrightStars.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-23786); [Jenkins run #34670](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/34670/pipeline)
> DM-23786: Add bright star subtraction task

- python/lsst/pipe/tasks/assembleCoadd.py
- python/lsst/pipe/tasks/functors.py
- tests/assembleCoaddTestUtils.py
- tests/surveyPropertyMapsTestUtils.py
- tests/test_finalizeCharacterization.py
- tests/test_functors.py
- tests/test_hips.py
- tests/test_isolatedStarAssociation.py
- tests/test_makeSurveyPropertyMaps.py
Many of the get() implementations here might Just Work using the default ExposureF delegate although the cloning going on makes me worried that the returned item is modified and so it won't work because we don't clone in the default delegate. We might also need to think about a way for an InMemoryDatasetHandle to specify a default dataId constructor and also whether additional kwargs can be stored and then retrieved later on.
Requires lsst/pipe_base#318
> DM-38091: Use InMemoryDatasetHandle

- python/lsst/pipe/tasks/functors.py
- tests/assembleCoaddTestUtils.py
- tests/test_functors.py
- tests/test_psfCandidateSelection.py
- tests/test_skySources.py
> DM-38694: Use InMemoryDatasetHandle in assemble coadd test

- python/lsst/pipe/tasks/functors.py
The doc string descriptions of ConvertPixelToArcseconds and ConvertPixelSqToArcsecondsSq were swapped. They have been switched to the correct functor.
> Swap pixel to arcsecond and squared version docstrings

- python/lsst/pipe/tasks/dataFrameActions/_actions.py
- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/skyCorrection.py
The aliasing for numpy.warnings no longer works.
> DM-39726: Use warnings instead of numpy.warnings

- tests/test_diff_matched_tract_catalog.py
This is necessary on intel, centos7, with rubinenv 7.
> DM-39763: Slightly relax precision of tests for rubinenv 7.

- python/lsst/pipe/tasks/makeWarp.py
> DM-36486: Remove the deprecated prepareCalibratedExposures

- tests/test_reinterpolate_pixels.py
I moved the unit test from `meas_algorithms` to `pipe_tasks` because it failed in Jenkins due to dependencies.
> DM-37332: Add task to re-interpolate mask planes

- pipelines/DRP.yaml
- pipelines/VisualizeVisit.yaml
Pipelines should go in *_pipe packages.
> DM-35579: Remove pipelines forwarding stubs.

- tests/test_import.py
> DM-35901: Use the new lsst.utils.tests.ImportTestCase class for import test

- schemas/Source.yaml
Because FGCM takes direct instrumental fluxes, and to enable running FGCM on LATISS.
> DM-40301: Add 35- and 50-pix inst fluxes to source tables

- python/lsst/pipe/tasks/hips.py
This also adds the ability to specify the Allsky file to be a jpeg or png.
> DM-40746: Fix size and shape of HiPS Allsky file.

- python/lsst/pipe/tasks/multiBand.py
- schemas/Object.yaml
- tests/test_isPrimaryFlag.py
Now that meas_extensions_scarlet will deblend footprints that only have partial coverage (eg. in one or more band there is missing data that prevents building a PSF), new columns were added to the catalog to mark sources that were not deblended in a given band.
> DM-40451: Update multiband measurement task for deblending with partial coverage

- python/lsst/pipe/tasks/mergeMeasurements.py
Needs to be merged after DM-40451-v24.
> DM-41008-v24: Do not include bands with no data in merge measurements

- python/lsst/pipe/tasks/healSparseMapping.py
This completes an incomplete fix on DM-37837.  Note that this was also fixed upstream in healsparse, so this makes it compatible with older versions, but also skips some unnecessary computations in all cases.
> DM-41303: Ensure that we skip empty maps that should not be appended.

- python/lsst/pipe/tasks/calibrate.py
- python/lsst/pipe/tasks/calibrateImage.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/finalizeCharacterization.py
- python/lsst/pipe/tasks/multiBand.py
- schemas/ForcedSource.yaml
- schemas/Object.yaml
- schemas/Source.yaml
This PR adds maskStreaksTask (with no bells or whistles) as a default step to single frame processing.
It supports both main "modes" of single frame: the original `isr -> characterizeImage -> calibrate` AS WELL AS the newfangled `isr -> calibrateImage`.
The result is that linear DETECTED features are also masked as STREAK.
> DM-32769: Implement streak detection and masking in single frame processing

- python/lsst/pipe/tasks/selectImages.py
This PR also fixes the logging of the seeing range used for selection.
> DM-41503: Allow BestSeeingSelectVisitsTask to select all visits below some fwhm cut

- tests/test_calibrateImage.py
The expectation is that TestDataset returns a catalog that looks like a measurement catalog, that means that it has coordErr fields and that the coord/coordErr fields are filled in from the pixel positions using the provided WCS.
> DM-41345: Let TestDataset handle coordinates

- python/lsst/pipe/tasks/characterizeImage.py
The config fields were removed because they had deprecations in place for over a year, and were deprecated because they never did anything in the first place.
> DM-34769: Remove characterizeImage refObjLoader

- python/lsst/pipe/tasks/calibrateImage.py
- python/lsst/pipe/tasks/computeExposureSummaryStats.py
- python/lsst/pipe/tasks/selectImages.py
This PR updates a few things for `psfStarScaledDeltaSizeScatter`:
a) Object sizes are now computed with the trace radius rather than the determinant radius (less noisy)
b) An explicit selector can be used to control the signal to noise of the size statistics.
c) The scaling factor is changed from size squared to size.
d) The default cut applied for coadds has been updated to 0.019 appropriate for this new definition, as determined from the reprocessing of HSC PDR2.
> DM-40668: Update computation of psfStarScaledDeltaSizeScatter

- tests/test_calibrate.py
This is a reasonable thing to do in general, but is important when using pytest-randomly because when using that plugin without the --randomly-dont-reset-seed flag, the seed is forced to the global value before every test is run. This leads to makeTestCollection returning the same random integer for every test and the runs clash in the shared repo.
> DM-41846: Use the test ID as the unique component of the test run collection

- tests/test_cliCmd.py
It shouldn't be possible to register a subfilter that references a band that doesn't exist; this is a variant of DM-40818.
*If* one does manage to register such a subfilter, querying for it with a band constraint (as the CLI script does) is ill-defined - should it return no records since the band does not exist?  Or should it return the referencing subfilter recoreds anyway?  The previous test assumed the latter, but changes to daf_butler on this ticket are changing the behavior to the former.  Registering the band (by registering an instrument and hence some physical_filters) first here avoids that ill-defined behavior, and it should make this test continue to work when DM-40818 is done.
> DM-42324: Make sure bands exist in DCR subfilter registration test.

- python/lsst/pipe/tasks/isolatedStarAssociation.py
- tests/test_calibrateImage.py
The selection/threshold is updated in meas_algorithms, but we also need to update the transformed column name for the isolated star association task.
> DM-42663: Use moments based classifier in isolatedStarAssociationTask.

- python/lsst/pipe/tasks/calibrateImage.py
This includes a temporary workaround to not break downstream tasks while [DM-43083](https://jira.lsstcorp.org/browse/DM-43083) is in progress, to be removed once masking happens in diffim.
[DM-43083]: https://rubinobs.atlassian.net/browse/DM-43083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DM-43080: Remove maskStreaks from CalibrateImageTask

- python/lsst/pipe/tasks/calibrateImage.py
- tests/test_calibrateImage.py
We may eventually want to turn this into a warning, but for now we need to know when this happens, as we try to understand how to tune star selection.
> DM-43247: Raise if no psf_stars match to selected stars

- python/lsst/pipe/tasks/calibrate.py
Added the ability to create and write metrics from the calexp summary stats. The task to calculate the metrics must be retargeted at runtime to avoid circular imports in calibrate. This is the reason for the private _EmptyTargetTask. This gets retargeted to CalexpSummaryTask in analysis tools, which is what creates the MetricMeasurementBundle that gets written to sasquatch.
> DM-43231: Create Analysis Tool to send visitSummary info to sasquatch

- python/lsst/pipe/tasks/makeWarp.py
This also partly covers the deprecation cleanup from DM-39854, at least as far as makeWarp.py is concerned.
> DM-43545: Ensure that images without psfs/aperture corrections are not used in warps.

- python/lsst/pipe/tasks/hips.py
This avoids using deprecated interfaces like
`Pipeline.toExpandedPipeline` while letting the base class handle a lot of details.
> DM-40441: Rewrite HiPS custom QG builder to inherit from new base class.

- COPYRIGHT
- doc/lsst.pipe.tasks/index.rst
- python/lsst/pipe/tasks/getRegionTimeFromVisit.py
- tests/test_getRegionTimeFromVisit.py
This PR adds an adapter task between AP "batch" processing (which has all the visit metadata in the visit dimension records) and Prompt Processing (which needs to get it from non-Butler sources). It's a prerequisite for several "preload" tasks in different packages.
This PR must be merged after lsst/daf_butler#999 and lsst/pipe_base#415, which provide necessary infrastructure.
> DM-43020: Implement region and time extraction for preload

- python/lsst/pipe/tasks/calibrateImage.py
list to be run before having a PSF model.
> DM-43973: Remove ClassificationSizeExtendedness from plugin

- python/lsst/pipe/tasks/calibrateImage.py
- python/lsst/pipe/tasks/characterizeImage.py
- python/lsst/pipe/tasks/finalizeCharacterization.py
This also adds additional comments about why `includeThresholdMultiplier` is an important config.
> DM-44246: Use full set of src footprints for noise replacement in FinalizeCharacterizationTask.

- python/lsst/pipe/tasks/visualizeVisit.py
Add variety of subclasses of task/config to support different input dimensions.
> DM-41442: Add focal plane mosaic construction to cp_pipe/cp_verify

- tests/test_cliCmd.py
- tests/test_matchFakes.py
Note that (a) for rings and discrete skymap these return almost the same polygon (which was incorrect necessitating the deprecation); (b) using the outer polygon may have been the original intention in the fakes task; (c) the fakes tasks are being replaced with the new source injection tasks.
> DM-44796: Replace deprecated getInnerSkyPolygon() with getOuterSkyPolygon()

- python/lsst/pipe/tasks/calibrate.py
The calibrate task now always runs normalized calibration, which can now handle empty aperture correction maps.
> DM-45002: Update calibrate to always run the normalized calibration.

- tests/test_calexpCutout.py
- tests/test_calibrate.py
- tests/test_isPrimaryFlag.py
- tests/test_photoCal.py
- tests/test_psfCandidateSelection.py
- tests/test_skySources.py
* Disable changes to global log levels (changing test order can break tests)
* Do not use getPackageDir when there is no need to.
* Minor edit to test_calibrate.py
> DM-45234: Some minor test cleanups

- python/lsst/pipe/tasks/fit_coadd_multiband.py
- python/lsst/pipe/tasks/fit_coadd_psf.py
If using shapelet PSF parameters, these are in the deepCoadd_meas catalog and so there's no need to try to load a multiprofit PSF fit table that might not even exist.
> DM-45577: Add option to drop PSF fit table connection

- python/lsst/pipe/tasks/getRegionTimeFromVisit.py
- tests/test_getRegionTimeFromVisit.py
This PR fixes a bug where `GetRegionTimeFromVisitTask` would cause analysis of quantum graphs to crash.
> DM-46699: Dummy output of GetRegionTimeFromVisitTask confuses provenance tools

- python/lsst/pipe/tasks/computeExposureSummaryStats.py
- python/lsst/pipe/tasks/postprocess.py
- tests/test_computeExposureSummaryStats.py
Simple computation of the magnitude limit at fixed SNR (e.g., SNR=5) from the psfSigma, skyBg, zeroPoint, and readNoise. See DM-45573, STMN-002, and LSE-40 for details.
> DM-45573: Compute magnitude limit for exposure summary stats

- python/lsst/pipe/tasks/finalizeCharacterization.py
- python/lsst/pipe/tasks/isolatedStarAssociation.py
In preparation for the great calibration refactor. PreSources will always be generated in single frame processing and have fewer rows than Sources based on a second round of more complete detection
- isolated_star_cat -> isolated_star_presource_associations
- isolated_star_sources -> isolated_star_presources
> DM-46642: Rename outputs of isolatedStarAssociation

- python/lsst/pipe/tasks/fit_coadd_multiband.py
This really should have been in the base class all along instead of being specific to MultiProFit - multiband fitters are going to have to specify which bands they fit one way or another and picking this option seems fine.
> DM-46627: Move bands_fit from MPF config to CoaddMultibandFitSubConfig

- schemas/PreSource.yaml
These need to differ only because they're being produced by different tasks with different ways of handling IDs.
I'm making minor adjustments instead of switching to the existing configuration for initial_stars_detector because I don't want to reconfigure downstream analysis tasks (which require many measurement columns that calibrateImage doesn't run by default) on this ticket.  I expect the final configuration to be somewhere in between.
> DM-46991: Add PreSource.yaml and update Source.yaml to work with calibrateImage.

- python/lsst/pipe/tasks/measurePsf.py
This will catch bad psfs returned from both psfex and piff.
Unfortunately, there are no tests for MeasurePsf, so there's not a good place to put a test of this new exception (e.g. with a mocked-bad psf). I checked it with one of the calibrateImage tests, removing the `not` and seeing that the appropriate exception was raised.
> DM-47787: Add check on psf size to MeasurePsfTask

- python/lsst/pipe/tasks/skyCorrection.py
- tests/test_skyCorrection.py
The current `SkyCorrectionTask` has three principal steps:
1. `bgModel1` - a large-scale sky estimation and subtraction
2.  `sky` - a subtraction of the sky frame
3.  `bgModel2` - a small-scale sky estimation and subtraction
If one has `doSky = True`, then `bgModel1` is implied. However, during testing of [DM-44889](https://rubinobs.atlassian.net/browse/DM-44889), it became apparent that the need for a `doSky = True` -only dataset output was required. This necessitates that `bgModel1` is generated, used, and then undone.
This ticket adds that functionality into the current `SkyCorrectionTask`. 
Note the prior related removal ticket of `doBgModel1`, [DM-37429](https://rubinobs.atlassian.net/browse/DM-37429), which may be relevant/of use here.
[DM-44889]: …
> DM-46693: Add ability to re-apply bgModel1 in SkyCorrectionTask

- python/lsst/pipe/tasks/loadReferenceCatalog.py
- tests/test_loadReferenceCatalog.py
The new implementation no longer assumes there is a refcat shard overlapping the center of a tract, which was important for ci_hsc.
> DM-47730: Use new refcat loader method to improve refcat flux field checks.

- python/lsst/pipe/tasks/drpAssociationPipe.py
drpAssociationPipe would fail when no diaSources were found due to an astropy-to-Pandas conversion on an empty Table with a datetime64 column. The solution checks to see if the Table is empty before converting, in which case it replaces the Table with a new empty DataFrame with matching columns.
> DM-49097 : Create empty DataFrame rather than convert from Table

- python/lsst/pipe/tasks/photoCal.py
While this exception was intended to be raised by the matcher itself, it seems quite appropriate to use it downstream when it's clearly a problem in the matching.
> DM-49161: Raise MatcherFailure on no matches in PhotoCalTask.

- python/lsst/pipe/tasks/coaddBase.py
- python/lsst/pipe/tasks/makeWarp.py
This also includes one commit that is not (yet) on main that just updates the release in which the deprecated interfaces will be removed after from v30 to v29, reflecting the fact that the deprecation is happening earlier. This commit will be added to main after the backport is complete.
> DM-49263-v29: Backport deprecating and disabling propagating photometric calibration uncertainty

- python/lsst/pipe/tasks/coaddBase.py
With the deprecations from DM-49263 now appearing in v29 due a backport, we also need to adjust the deprecation clock on main.
> DM-49263-v29: Shift removal to post-v29 to reflect deprecation in v29 (forward-port)

- python/lsst/pipe/tasks/functors.py
- schemas/Source.yaml
- tests/test_functors.py
This also fixes an associativity bug in the dipole mean flux uncertainty calculation that had been masked by the PhotoCalib uncertainty in the test being exactly one.
> DM-49452: Disable and deprecate propagating PhotoCalib uncertainty in functors.

- python/lsst/pipe/tasks/functors.py
- schemas/Source.yaml
- tests/test_functors.py
This also fixes an associativity bug in the dipole mean flux uncertainty calculation that had been masked by the PhotoCalib uncertainty in the test being exactly one.
> DM-49452-v29: Disable and deprecate propagating PhotoCalib uncertainty in functors.

- python/lsst/pipe/tasks/functors.py
- python/lsst/pipe/tasks/postprocess.py
- schemas/Object.yaml
- tests/test_transformObject.py
This is a minimally altered version of ObjectEpochTableTask from analysis_tools (which I intend to deprecate shortly) but using `deepCoadd_obj` as an input instead of `objectTable`, so that it can more easily be merged into `objectTable`.
> DM-49727: Add ComputeObjectEpochsTask

- python/lsst/pipe/tasks/hips.py
This change set 
* adds lsstRGB image format to hips image generation as an option
* adds the ability to output in webp image format
* adds the option to run hips generation in a somewhat parallel way.
> DM-47711 Add lsstRGB image format to hips code generation (and make it somewhat parallel)

- python/lsst/pipe/tasks/finalizeCharacterization.py
These mapping keys are required for reprocessing the final visit image.
> DM-49970: Add normalized calib flux to finalized aperture correction map.

- python/lsst/pipe/tasks/photoCal.py
The resulting error looks like:
```
lsst.meas.astrom.exceptions.MatcherFailure: No matched reference stars with valid fluxes: {'goodSrc': 369, 'goodRef': 0}
```
> DM-50695: Raise MatcherError if no reference sources have finite flux

- python/lsst/pipe/tasks/skyCorrection.py
The existing legacy HSC config value of bgModel2.minFrac=0.5 served to exclude fields whereby a large fraction of data was lost due to, e.g., bright stars. For Rubin, we hit this threshold more often due to crowded fields (see postage stamp links on DM-51429 as evidence). To that end, here we reduce the bgModel2.minFrac config to 0.3. The background task default (used for bgModel1) is 0.1. Therefore, 0.3 is still somewhat conservative, helping to guard against low-number statistics in very crowded fields. However, testing shows that reducing this value to 0.3 appears to work without any adverse results.
> DM-51429: Modify skyCorr bgModel2 minFrac to 0.3
